export const FEATURES = [
  // AI Features
  {
    key: 'weather-forecasts',
    title: 'Weather Demand Forecasting',
    description: 'AI-powered demand predictions based on weather patterns, historical data, and seasonal trends.',
    icon: '🌤️',
    color: '#f59e0b',
    isAI: true,
    endpoint: 'weather-forecasts',
    aiEndpoint: 'weather-forecast',
    aiLabel: 'Run AI Forecast',
    aiParam: 'location_id',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'location_id', label: 'Location' },
      { key: 'forecast_date', label: 'Date', format: 'date' },
      { key: 'condition', label: 'Condition' },
      { key: 'temp_high', label: 'High °F' },
      { key: 'precipitation_chance', label: 'Rain %' },
      { key: 'predicted_demand', label: 'Demand', format: 'status' },
      { key: 'predicted_cars', label: 'Cars' },
    ],
    fields: [
      { key: 'location_id', label: 'Location ID', type: 'number', required: true },
      { key: 'forecast_date', label: 'Date', type: 'date', required: true },
      { key: 'condition', label: 'Condition', type: 'select', options: ['Sunny', 'Partly Cloudy', 'Overcast', 'Rainy', 'Thunderstorm', 'Windy', 'Hot', 'Drizzle'], required: true },
      { key: 'temp_high', label: 'High Temp (°F)', type: 'number' },
      { key: 'temp_low', label: 'Low Temp (°F)', type: 'number' },
      { key: 'precipitation_chance', label: 'Precipitation %', type: 'number' },
      { key: 'humidity', label: 'Humidity %', type: 'number' },
      { key: 'predicted_demand', label: 'Predicted Demand', type: 'select', options: ['very_low', 'low', 'medium', 'high', 'very_high'] },
      { key: 'predicted_cars', label: 'Predicted Cars', type: 'number' },
      { key: 'ai_recommendation', label: 'AI Recommendation', type: 'textarea' },
    ],
    detailFields: ['location_id', 'forecast_date', 'condition', 'temp_high', 'temp_low', 'precipitation_chance', 'humidity', 'predicted_demand', 'predicted_cars', 'ai_recommendation'],
  },
  {
    key: 'chemical-dosing',
    title: 'Chemical Dosing Optimization',
    description: 'AI optimizes chemical usage based on water hardness, temperature, and soil levels for cost savings.',
    icon: '🧪',
    color: '#06b6d4',
    isAI: true,
    endpoint: 'chemical-dosing',
    aiEndpoint: 'chemical-dosing',
    aiLabel: 'Optimize Dosing',
    aiParam: 'location_id',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'chemical_id', label: 'Chemical' },
      { key: 'location_id', label: 'Location' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'water_hardness', label: 'Hardness' },
      { key: 'vehicle_soil_level', label: 'Soil Level' },
      { key: 'recommended_dosage', label: 'Recommended' },
      { key: 'effectiveness_score', label: 'Score' },
    ],
    fields: [
      { key: 'chemical_id', label: 'Chemical ID', type: 'number', required: true },
      { key: 'location_id', label: 'Location ID', type: 'number', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'water_hardness', label: 'Water Hardness (ppm)', type: 'number' },
      { key: 'temperature', label: 'Temperature (°F)', type: 'number' },
      { key: 'vehicle_soil_level', label: 'Soil Level', type: 'select', options: ['light', 'medium', 'heavy'] },
      { key: 'recommended_dosage', label: 'Recommended Dosage', type: 'number' },
      { key: 'actual_dosage', label: 'Actual Dosage', type: 'number' },
      { key: 'effectiveness_score', label: 'Effectiveness Score', type: 'number' },
      { key: 'ai_optimization', label: 'AI Optimization Notes', type: 'textarea' },
    ],
    detailFields: ['chemical_id', 'location_id', 'date', 'water_hardness', 'temperature', 'vehicle_soil_level', 'recommended_dosage', 'actual_dosage', 'effectiveness_score', 'ai_optimization'],
  },
  {
    key: 'maintenance-predictions',
    title: 'Equipment Maintenance Predictor',
    description: 'AI predicts equipment failures before they happen, reducing downtime and repair costs.',
    icon: '🔧',
    color: '#ef4444',
    isAI: true,
    endpoint: 'maintenance-predictions',
    aiEndpoint: 'maintenance-prediction',
    aiLabel: 'Predict Maintenance',
    aiParam: 'equipment_id',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'equipment_id', label: 'Equipment' },
      { key: 'predicted_failure_date', label: 'Failure Date', format: 'date' },
      { key: 'confidence', label: 'Confidence %' },
      { key: 'risk_level', label: 'Risk', format: 'status' },
      { key: 'estimated_cost', label: 'Est. Cost', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'equipment_id', label: 'Equipment ID', type: 'number', required: true },
      { key: 'predicted_failure_date', label: 'Predicted Failure Date', type: 'date' },
      { key: 'confidence', label: 'Confidence %', type: 'number' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'recommended_action', label: 'Recommended Action', type: 'textarea' },
      { key: 'estimated_cost', label: 'Estimated Cost', type: 'number' },
      { key: 'parts_needed', label: 'Parts Needed', type: 'text' },
      { key: 'ai_analysis', label: 'AI Analysis', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'urgent', 'scheduled', 'monitoring', 'completed'] },
    ],
    detailFields: ['equipment_id', 'predicted_failure_date', 'confidence', 'risk_level', 'recommended_action', 'estimated_cost', 'parts_needed', 'ai_analysis', 'status'],
  },
  {
    key: 'staffing',
    title: 'Smart Staffing Optimizer',
    description: 'AI creates optimal staff schedules based on demand forecasts, weather, and employee availability.',
    icon: '👥',
    color: '#8b5cf6',
    isAI: true,
    endpoint: 'staffing',
    aiEndpoint: 'staffing-optimization',
    aiLabel: 'Optimize Staffing',
    aiParam: 'location_id',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'location_id', label: 'Location' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'shift', label: 'Shift' },
      { key: 'required_staff', label: 'Staff Needed' },
      { key: 'predicted_demand', label: 'Demand', format: 'status' },
      { key: 'labor_cost', label: 'Labor Cost', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'location_id', label: 'Location ID', type: 'number', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'shift', label: 'Shift', type: 'select', options: ['morning', 'afternoon', 'evening'], required: true },
      { key: 'required_staff', label: 'Required Staff', type: 'number' },
      { key: 'predicted_demand', label: 'Predicted Demand', type: 'select', options: ['very_low', 'low', 'medium', 'high', 'very_high'] },
      { key: 'weather_factor', label: 'Weather Factor', type: 'number' },
      { key: 'employee_ids', label: 'Employee IDs (comma-separated)', type: 'text' },
      { key: 'labor_cost', label: 'Labor Cost', type: 'number' },
      { key: 'ai_recommendation', label: 'AI Recommendation', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'confirmed', 'completed'] },
    ],
    detailFields: ['location_id', 'date', 'shift', 'required_staff', 'predicted_demand', 'weather_factor', 'employee_ids', 'labor_cost', 'ai_recommendation', 'status'],
  },
  {
    key: 'memberships',
    title: 'Membership Churn Prediction',
    description: 'AI identifies at-risk members and suggests personalized retention strategies.',
    icon: '🔄',
    color: '#ec4899',
    isAI: true,
    endpoint: 'memberships',
    aiEndpoint: 'churn-prediction',
    aiLabel: 'Predict Churn',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'customer_name', label: 'Customer' },
      { key: 'plan_type', label: 'Plan' },
      { key: 'monthly_price', label: 'Price', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'washes_this_month', label: 'Washes' },
      { key: 'churn_risk', label: 'Churn Risk %' },
      { key: 'renewal_date', label: 'Renewal', format: 'date' },
    ],
    fields: [
      { key: 'customer_name', label: 'Customer Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email', required: true },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'plan_type', label: 'Plan Type', type: 'select', options: ['Basic', 'Premium', 'Ultimate'], required: true },
      { key: 'monthly_price', label: 'Monthly Price', type: 'number', required: true },
      { key: 'location_id', label: 'Location ID', type: 'number' },
      { key: 'start_date', label: 'Start Date', type: 'date', required: true },
      { key: 'renewal_date', label: 'Renewal Date', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'paused', 'expired', 'cancelled'] },
      { key: 'washes_this_month', label: 'Washes This Month', type: 'number' },
      { key: 'lifetime_value', label: 'Lifetime Value', type: 'number' },
      { key: 'churn_risk', label: 'Churn Risk %', type: 'number' },
    ],
    detailFields: ['customer_name', 'email', 'phone', 'plan_type', 'monthly_price', 'location_id', 'start_date', 'renewal_date', 'status', 'washes_this_month', 'lifetime_value', 'churn_risk'],
  },
  {
    key: 'revenue',
    title: 'Revenue Optimizer',
    description: 'AI analyzes revenue patterns and suggests pricing, upsell, and promotional strategies.',
    icon: '💰',
    color: '#22c55e',
    isAI: true,
    endpoint: 'revenue',
    aiEndpoint: 'revenue-optimization',
    aiLabel: 'Optimize Revenue',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'location_id', label: 'Location' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'total_revenue', label: 'Revenue', format: 'currency' },
      { key: 'total_cars', label: 'Cars' },
      { key: 'avg_ticket', label: 'Avg Ticket', format: 'currency' },
      { key: 'membership_revenue', label: 'Membership $', format: 'currency' },
      { key: 'top_service', label: 'Top Service' },
    ],
    fields: [
      { key: 'location_id', label: 'Location ID', type: 'number', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'total_revenue', label: 'Total Revenue', type: 'number' },
      { key: 'total_cars', label: 'Total Cars', type: 'number' },
      { key: 'avg_ticket', label: 'Avg Ticket', type: 'number' },
      { key: 'membership_revenue', label: 'Membership Revenue', type: 'number' },
      { key: 'walk_in_revenue', label: 'Walk-in Revenue', type: 'number' },
      { key: 'top_service', label: 'Top Service', type: 'text' },
      { key: 'ai_insights', label: 'AI Insights', type: 'textarea' },
    ],
    detailFields: ['location_id', 'date', 'total_revenue', 'total_cars', 'avg_ticket', 'membership_revenue', 'walk_in_revenue', 'top_service', 'ai_insights'],
  },
  {
    key: 'feedback',
    title: 'Customer Sentiment Analysis',
    description: 'AI analyzes customer feedback to identify trends, issues, and improvement opportunities.',
    icon: '💬',
    color: '#14b8a6',
    isAI: true,
    endpoint: 'feedback',
    aiEndpoint: 'sentiment-analysis',
    aiLabel: 'Analyze Sentiment',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'customer_id', label: 'Customer' },
      { key: 'location_id', label: 'Location' },
      { key: 'rating', label: 'Rating' },
      { key: 'service_type', label: 'Service' },
      { key: 'sentiment', label: 'Sentiment', format: 'status' },
      { key: 'sentiment_score', label: 'Score' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'customer_id', label: 'Customer ID', type: 'number' },
      { key: 'location_id', label: 'Location ID', type: 'number' },
      { key: 'rating', label: 'Rating (1-5)', type: 'number', required: true },
      { key: 'comment', label: 'Comment', type: 'textarea', required: true },
      { key: 'service_date', label: 'Service Date', type: 'date' },
      { key: 'service_type', label: 'Service Type', type: 'text' },
      { key: 'sentiment', label: 'Sentiment', type: 'select', options: ['positive', 'neutral', 'negative'] },
      { key: 'sentiment_score', label: 'Sentiment Score', type: 'number' },
      { key: 'ai_analysis', label: 'AI Analysis', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['new', 'reviewed', 'in_progress', 'escalated', 'resolved'] },
    ],
    detailFields: ['customer_id', 'location_id', 'rating', 'comment', 'service_date', 'service_type', 'sentiment', 'sentiment_score', 'ai_analysis', 'status'],
  },
  {
    key: 'energy',
    title: 'Energy Usage Optimizer',
    description: 'AI monitors and optimizes energy consumption, water usage, and sustainability metrics.',
    icon: '⚡',
    color: '#eab308',
    isAI: true,
    endpoint: 'energy',
    aiEndpoint: 'energy-optimization',
    aiLabel: 'Optimize Energy',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'location_id', label: 'Location' },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'electricity_kwh', label: 'kWh' },
      { key: 'water_gallons', label: 'Water (gal)' },
      { key: 'total_cost', label: 'Cost', format: 'currency' },
      { key: 'cars_washed', label: 'Cars' },
      { key: 'cost_per_car', label: '$/Car', format: 'currency' },
    ],
    fields: [
      { key: 'location_id', label: 'Location ID', type: 'number', required: true },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'electricity_kwh', label: 'Electricity (kWh)', type: 'number' },
      { key: 'water_gallons', label: 'Water (gallons)', type: 'number' },
      { key: 'gas_therms', label: 'Gas (therms)', type: 'number' },
      { key: 'total_cost', label: 'Total Cost', type: 'number' },
      { key: 'cars_washed', label: 'Cars Washed', type: 'number' },
      { key: 'cost_per_car', label: 'Cost Per Car', type: 'number' },
      { key: 'ai_optimization', label: 'AI Optimization', type: 'textarea' },
    ],
    detailFields: ['location_id', 'date', 'electricity_kwh', 'water_gallons', 'gas_therms', 'total_cost', 'cars_washed', 'cost_per_car', 'ai_optimization'],
  },
  // Non-AI Management Features
  {
    key: 'locations',
    title: 'Location Management',
    description: 'Manage all car wash locations, operating hours, capacity, and performance metrics.',
    icon: '📍',
    color: '#3b82f6',
    isAI: false,
    endpoint: 'locations',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'capacity', label: 'Capacity' },
      { key: 'operating_hours', label: 'Hours' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'monthly_revenue', label: 'Revenue', format: 'currency' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'address', label: 'Address', type: 'text', required: true },
      { key: 'city', label: 'City', type: 'text', required: true },
      { key: 'state', label: 'State', type: 'text', required: true },
      { key: 'zip', label: 'ZIP', type: 'text', required: true },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'capacity', label: 'Capacity', type: 'number' },
      { key: 'operating_hours', label: 'Operating Hours', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'maintenance', 'closed'] },
      { key: 'monthly_revenue', label: 'Monthly Revenue', type: 'number' },
    ],
    detailFields: ['name', 'address', 'city', 'state', 'zip', 'phone', 'capacity', 'operating_hours', 'status', 'monthly_revenue', 'lat', 'lng'],
  },
  {
    key: 'equipment',
    title: 'Equipment Inventory',
    description: 'Track all car wash equipment, health scores, maintenance schedules, and operational status.',
    icon: '⚙️',
    color: '#64748b',
    isAI: false,
    endpoint: 'equipment',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'location_id', label: 'Location' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'health_score', label: 'Health %' },
      { key: 'hours_used', label: 'Hours' },
      { key: 'next_maintenance', label: 'Next Maint.', format: 'date' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Conveyor System', 'Pressure Washer', 'Chemical Dispenser', 'Air Dryer', 'Wheel Washer', 'Water System', 'Brush System', 'POS System', 'Vacuum System', 'Signage'], required: true },
      { key: 'location_id', label: 'Location ID', type: 'number' },
      { key: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { key: 'model', label: 'Model', type: 'text' },
      { key: 'install_date', label: 'Install Date', type: 'date' },
      { key: 'last_maintenance', label: 'Last Maintenance', type: 'date' },
      { key: 'next_maintenance', label: 'Next Maintenance', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['operational', 'needs_maintenance', 'critical', 'offline'] },
      { key: 'health_score', label: 'Health Score', type: 'number' },
      { key: 'hours_used', label: 'Hours Used', type: 'number' },
      { key: 'purchase_cost', label: 'Purchase Cost', type: 'number' },
    ],
    detailFields: ['name', 'type', 'location_id', 'manufacturer', 'model', 'install_date', 'last_maintenance', 'next_maintenance', 'status', 'health_score', 'hours_used', 'purchase_cost'],
  },
  {
    key: 'employees',
    title: 'Employee Management',
    description: 'Manage staff profiles, performance scores, certifications, scheduling, and payroll data.',
    icon: '🧑‍💼',
    color: '#a855f7',
    isAI: false,
    endpoint: 'employees',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'role', label: 'Role' },
      { key: 'location_id', label: 'Location' },
      { key: 'hourly_rate', label: 'Rate', format: 'currency' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'performance_score', label: 'Perf. Score' },
      { key: 'hours_per_week', label: 'Hrs/Week' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'role', label: 'Role', type: 'select', options: ['Site Manager', 'Wash Technician', 'Equipment Technician', 'Customer Service'], required: true },
      { key: 'location_id', label: 'Location ID', type: 'number' },
      { key: 'hourly_rate', label: 'Hourly Rate', type: 'number', required: true },
      { key: 'hire_date', label: 'Hire Date', type: 'date', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'on_leave'] },
      { key: 'hours_per_week', label: 'Hours/Week', type: 'number' },
      { key: 'performance_score', label: 'Performance Score', type: 'number' },
      { key: 'certifications', label: 'Certifications', type: 'text' },
    ],
    detailFields: ['name', 'email', 'phone', 'role', 'location_id', 'hourly_rate', 'hire_date', 'status', 'hours_per_week', 'performance_score', 'certifications'],
  },
  {
    key: 'chemicals',
    title: 'Chemical Inventory',
    description: 'Track chemical supplies, reorder levels, safety ratings, and supplier information.',
    icon: '🧴',
    color: '#0ea5e9',
    isAI: false,
    endpoint: 'chemicals',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'unit_cost', label: 'Cost', format: 'currency' },
      { key: 'quantity_on_hand', label: 'Qty' },
      { key: 'reorder_level', label: 'Reorder At' },
      { key: 'safety_rating', label: 'Safety' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['Pre-soak', 'Polish/Wax', 'Degreaser', 'Rinse Aid', 'Tire Cleaner', 'Bug Remover', 'Sealant', 'Wheel Cleaner', 'Foam Soap', 'Rinse', 'Undercarriage', 'All-Purpose', 'Rust Inhibitor', 'Fragrance', 'Wax'], required: true },
      { key: 'supplier', label: 'Supplier', type: 'text' },
      { key: 'unit_cost', label: 'Unit Cost', type: 'number', required: true },
      { key: 'quantity_on_hand', label: 'Quantity On Hand', type: 'number' },
      { key: 'unit', label: 'Unit', type: 'select', options: ['gallons', 'liters', 'pounds', 'ounces'] },
      { key: 'reorder_level', label: 'Reorder Level', type: 'number' },
      { key: 'optimal_dosage', label: 'Optimal Dosage', type: 'number' },
      { key: 'location_id', label: 'Location ID', type: 'number' },
      { key: 'ph_level', label: 'pH Level', type: 'number' },
      { key: 'safety_rating', label: 'Safety Rating', type: 'select', options: ['eco-safe', 'standard', 'caution', 'hazardous'] },
    ],
    detailFields: ['name', 'type', 'supplier', 'unit_cost', 'quantity_on_hand', 'unit', 'reorder_level', 'optimal_dosage', 'location_id', 'last_ordered', 'ph_level', 'safety_rating'],
  },
  {
    key: 'service-packages',
    title: 'Service Packages',
    description: 'Manage wash packages, pricing, inclusions, and track popularity and profitability.',
    icon: '📦',
    color: '#f97316',
    isAI: false,
    endpoint: 'service-packages',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'price', label: 'Price', format: 'currency' },
      { key: 'wash_type', label: 'Type' },
      { key: 'duration_minutes', label: 'Duration' },
      { key: 'popularity_score', label: 'Popularity' },
      { key: 'profit_margin', label: 'Margin %' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'price', label: 'Price', type: 'number', required: true },
      { key: 'duration_minutes', label: 'Duration (min)', type: 'number' },
      { key: 'wash_type', label: 'Wash Type', type: 'select', options: ['express', 'basic', 'deluxe', 'premium', 'ultimate', 'detail', 'membership', 'fleet', 'specialty', 'seasonal'], required: true },
      { key: 'includes_interior', label: 'Interior', type: 'checkbox' },
      { key: 'includes_wax', label: 'Wax', type: 'checkbox' },
      { key: 'includes_tire', label: 'Tire Shine', type: 'checkbox' },
      { key: 'includes_underbody', label: 'Underbody', type: 'checkbox' },
      { key: 'popularity_score', label: 'Popularity Score', type: 'number' },
      { key: 'profit_margin', label: 'Profit Margin %', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    detailFields: ['name', 'description', 'price', 'duration_minutes', 'wash_type', 'includes_interior', 'includes_wax', 'includes_tire', 'includes_underbody', 'popularity_score', 'profit_margin', 'status'],
  },
  {
    key: 'customers',
    title: 'Customer Management',
    description: 'Track customer profiles, visit history, preferences, and satisfaction scores.',
    icon: '👤',
    color: '#6366f1',
    isAI: false,
    endpoint: 'customers',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'vehicle_type', label: 'Vehicle' },
      { key: 'preferred_location', label: 'Location' },
      { key: 'total_visits', label: 'Visits' },
      { key: 'total_spent', label: 'Total Spent', format: 'currency' },
      { key: 'last_visit', label: 'Last Visit', format: 'date' },
      { key: 'satisfaction_score', label: 'Satisfaction' },
    ],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'vehicle_type', label: 'Vehicle Type', type: 'text' },
      { key: 'vehicle_plate', label: 'License Plate', type: 'text' },
      { key: 'preferred_location', label: 'Preferred Location ID', type: 'number' },
      { key: 'total_visits', label: 'Total Visits', type: 'number' },
      { key: 'total_spent', label: 'Total Spent', type: 'number' },
      { key: 'last_visit', label: 'Last Visit', type: 'date' },
      { key: 'satisfaction_score', label: 'Satisfaction Score', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    detailFields: ['name', 'email', 'phone', 'vehicle_type', 'vehicle_plate', 'preferred_location', 'total_visits', 'total_spent', 'last_visit', 'satisfaction_score', 'membership_id', 'notes'],
  },
];
